name: CI New

on:
  push: # This now triggers on pushes to any branch
permissions:
  pull-requests: write
  contents: write

jobs:
  Run:
    uses: efabless/BusWrap/.github/workflows/run_ip.yaml@test-ci
    secrets: inherit
    with:
      repo: ${{ github.repository }}
      name: ${{ github.event.repository.name }}
      fw: true
      docs: true
      bus_wrapper: true
      pr_base: ${{ github.head_ref || github.ref_name }}
      pr_branch: "ci-ip-IP_BRANCH-BUSWRAP_COMMIT"
      pr_title: "ci[ip]: run bus_wrap(BUSWRAP_COMMIT) on IP_NAME(IP_BRANCH)"
      commit_msg: "run bus_wrap(BUSWRAP_COMMIT) on IP_NAME(IP_COMMIT)"
